services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qWxdxHPwqEEIBZckfQsWIdUaQKDseiaD
      POSTGRES_DB: railway
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

  api:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: f1e2d3a4b5c67890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
      RESET_EXPIRE_MINUTES: 30
      FRONTEND_RESET_URL: https://thesis-scan.vercel.app/studResetPass.html
      DATABASE_URL: postgresql://postgres:qWxdxHPwqEEIBZckfQsWIdUaQKDseiaD@gondola.proxy.rlwy.net:13656/railway
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      EMAIL_USER: alyasgdrive@gmail.com
      EMAIL_PASS: "cnsb vlzc zgmc rzsd"
      EMAIL_FROM_NAME: ThesiScan

volumes:
  db_data:
